config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get '/orders/search/:code', to: 'homepage#index'
  devise_for :users
  resources :budget_histories , only: [:index]
  resources :carriers, only: [:index, :new, :show, :new, :create, :edit, :update] do
    resources :vehicles, only: [:new, :create, :show]
    resources :prices, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :deadlines, only: [:new, :create, :edit, :update, :index, :destroy]
    patch 'inactivate', on: :member
    patch 'reactivate', on: :member
  end
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    resources :order_updates, only: [:index, :new, :create]
    member do
      patch 'accept'
      patch 'reject'
      patch 'select_vehicle'
      patch 'finish'
    end
    collection do
      get 'search'
      get 'budgets'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index] do
        collection do
          get '/search/:code', to: 'orders#search'
        end
      end
    end
  end
end

app/models/carrier.rb
class Carrier < ApplicationRecord
  validates :fantasy_name, :cnpj, :domain, :email, :address, presence: true
  validates :cnpj, length: { is: 14 }, numericality: true
  validates :fantasy_name, :cnpj, :email, :domain, uniqueness: true

  enum status: {active: 1, inactive: 2}

  has_many :vehicles
  has_many :prices
  has_many :deadlines
  has_many :orders
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :authenticate_user!
  def index
    @carriers = Carrier.all
  end

  def show
    @carrier = Carrier.find(params[:id])
    return unless current_user && !current_user.admin?

    @vehicles = @carrier.vehicles
  end

  def new
    @carrier = Carrier.new
  end

  def create
    carrier_params = params.require(:carrier).permit(:fantasy_name, :cnpj, :domain, :email, :address)

    @carrier = Carrier.new(carrier_params)

    if @carrier.save
      redirect_to @carrier, notice: 'Transportadora cadastrada com sucesso.'
    else
      flash.now[:notice] = 'Preencha os campos corretamente'
      render :new
    end
  end

  def edit
    @carrier = Carrier.find(params[:id])
  end

  def update
    @carrier = Carrier.find(params[:id])
    carrier_params = params.require(:carrier).permit(:fantasy_name, :cnpj, :domain, :email, :address)

    if @carrier.update(carrier_params)
      redirect_to @carrier, notice: 'Transportadora atualizada com sucesso.'
    else
      flash.now[:notice] = 'Preencha os campos corretamente'
      render :edit
    end
  end

  def inactivate
    carrier = Carrier.find(params[:id])
    carrier.inactive!
    carrier.save
    redirect_to carriers_path
  end

  def reactivate
    carrier = Carrier.find(params[:id])
    carrier.active!
    carrier.save
    redirect_to carriers_path
  end
end

app/views/carriers/_formc.html.erb
<section class=' pt-28 flex justify-center items-center h-full px-[3%]'>
  <%= form_with model: @carrier, html: {class:' h-[90%] items-center flex'}, data: { turbo: false } do |f| %>
    <div class=' flex flex-col text-black bg-slate-300 justify-center items-center p-10 m-auto'>
      <h2 class=' text-2xl font-bold pb-10'>Cadastro de Transportadora</h2>
      <div class='flex flex-col'>
      <div class='field pb-3'>
        <%= f.label :fantasy_name %><br />
        <%= f.text_field :fantasy_name, class:'rounded-2xl' %>
        <% if @carrier.errors.any?%>
          <p class=' text-red-600'><%= @carrier.errors.full_messages_for(:fantasy_name).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :cnpj %><br />
        <%= f.text_field :cnpj, class:'rounded-2xl' %>
        <% if @carrier.errors.any?%>
          <p class=' text-red-600'><%= @carrier.errors.full_messages_for(:cnpj).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :domain %><br />
        <%= f.text_field :domain, class:'rounded-2xl' %>
        <% if @carrier.errors.any?%>
          <p class=' text-red-600'><%= @carrier.errors.full_messages_for(:domain).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :email %><br />
        <%= f.text_field :email, class:'rounded-2xl' %>
        <% if @carrier.errors.any?%>
          <p class=' text-red-600'><%= @carrier.errors.full_messages_for(:email).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :address %><br />
        <%= f.text_field :address, class:'rounded-2xl' %>
        <% if @carrier.errors.any?%>
          <p class=' text-red-600'><%= @carrier.errors.full_messages_for(:address).first %></p>
        <% end %>
      </div>

      <div class='button_send'>
        <%= f.submit 'Enviar', class: 'bg-blue-500 hover:bg-blue-700 text-white font-semibold py-1 px-3 rounded-xl text-sm cursor-pointer text-xl'%>
      </div>
      </div>
    </div>
  <% end %>
</section>

app/views/carriers/edit.html.erb
<section>
  <div>
    <h2>Edição de Transportadora</h2>
  </div>
  <div>
    <%= render 'formc'%>
  </div>
</section>

app/views/carriers/index.html.erb
<section class=' pt-24 h-full px-[3%]'>
  <div class=' max-w-7xl mx-auto'>
    <h1 class='text-2xl font-bold pb-4'>Transportadoras</h1>
    <div>
      <%= button_to 'Cadastrar', new_carrier_path, method: :get, class: 'mb-2 bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl text-sm w-20 mr-2 '%>
    </div>
    <% if @carriers.empty?%>
      <div>
        <p>Não há transportadoras cadastradas</p>
      </div>
    <% else %>
    <div class='bg-slate-300 p-5 flex justify-center'>
      <table class='prices min-w-[100%]  bg-slate-300 p-5'>
        <thead>
          <tr class=' text-left'>
            <th>Nome</th>
            <th>CNPJ</th>
            <th>Domínio</th>
            <th>Endereço</th>
            <th>Email</th>
            <th>Ações</th>
            <th>Estado</th>
          </tr>
        </thead>
        <tbody>
        <% @carriers.each do |c|%>
            <tr>
              <td><%= link_to c.fantasy_name, c %></td>
              <td><%= c.cnpj %></td>
              <td><%= c.domain %></td>
              <td><%= c.address %></td>
              <td><%= c.email %></td>
              <% if c.active? %>
              <td><%= button_to 'Inativar', inactivate_carrier_path(c), method: :patch, class: 'bg-red-500 hover:bg-red-700 text-white px-1 rounded-xl text-sm w-20 mr-2 ' %></td>
              <%else%>
              <td><%= button_to 'Ativar', reactivate_carrier_path(c), method: :patch, class: 'bg-red-500 hover:bg-red-700 text-white px-1 rounded-xl text-sm w-20 mr-2 ' %></td>
              <% end %>
              <td><%= t c.status %></td>
            </tr>
        <%end%>
        </tbody>
      </table>
    </div>
    <%end%>
  </div>
</section>

app/views/carriers/new.html.erb
<section>
  <div>
    <%= render 'formc'%>
  </div>
</section>

app/views/carriers/show.html.erb
<section  class=' pt-28 h-full px-[3%]'>
  <%= button_to 'Voltar', root_path, method: :get, class: 'mt-2 float-right bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl text-sm w-14 mr-2 ' %>
  <div class='flex'>
    <div class= 'mx-20 w-1/5'>
      <h1 class=' text-xl font-bold pb-2'><%= @carrier.fantasy_name %></h1>
      <div>

        <p>CNPJ: <%= @carrier.cnpj %></p>
        <p>Email: <%= @carrier.email %></p>
        <p>Domínio: <%= @carrier.domain %></p>
        <p>Endereço: <%= @carrier.address %></p>
      </div>
      <div>
        <%= button_to 'Editar', edit_carrier_path, method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white my-3 py-1 px-2 rounded-xl text-sm w-14 mr-2 ' %>
      </div>
    </section>

    <section class='mx-6 w-4/5'>
      <h1 class=' text-xl font-semibold'>Veiculos</h1>

      <% if @vehicles && @vehicles.empty?%>
      <div>
        <p>Não há veiculos cadastrados</p>
      </div>
    <% elsif @vehicles %>
      <div class='py-5 flex justify-start w-full '>
        <table class='vehicles min-w-[70%]'>
          <thead>
            <tr class= ' text-left'>
              <th>Marca</th>
              <th>Modelo</th>
              <th>Placa</th>
              <th>Links</th>
            </tr>
          </thead>
          <tbody>
          <% @vehicles.each do |v|%>
              <tr>
                <td><%= v.brand%></td>
                <td><%= v.model %></td>
                <td><%= v.plate %></td>
                <td><%= button_to 'Detalhes', carrier_vehicle_path(current_user.carrier, v), method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white px-2 rounded-xl text-sm w-18 mr-2 '  %></td>
              </tr>
          <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
    <%= button_to 'Novo veiculo', new_carrier_vehicle_path(@carrier), method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white px-2 py-1 rounded-xl text-sm w-18 mr-2 '   %>
    </div>
  <div>
  </section>