config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get '/orders/search/:code', to: 'homepage#index'
  devise_for :users
  resources :budget_histories , only: [:index]
  resources :carriers, only: [:index, :new, :show, :new, :create, :edit, :update] do
    resources :vehicles, only: [:new, :create, :show]
    resources :prices, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :deadlines, only: [:new, :create, :edit, :update, :index, :destroy]
    patch 'inactivate', on: :member
    patch 'reactivate', on: :member
  end
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    resources :order_updates, only: [:index, :new, :create]
    member do
      patch 'accept'
      patch 'reject'
      patch 'select_vehicle'
      patch 'finish'
    end
    collection do
      get 'search'
      get 'budgets'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index] do
        collection do
          get '/search/:code', to: 'orders#search'
        end
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pendente: 1, Aceito: 2, Recusado: 3, Enviado: 4, Finalizado: 5, Cancelado:6}

  validates :status, :zip_code, :cubic_size,  :pickup_address, :receiver_address, :receiver_cpf, :receiver_name, :receiver_phone, presence: true
  validates :receiver_cpf, length: { is: 11 }, numericality: true
  validates :cubic_size, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :vehicle, optional: true
  belongs_to :carrier
  has_many :order_updates
  before_create :generator_code, :calc_freigth

  def generator_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def calc_freigth
    return unless zip_code || cubic_size

    price = Price.where(carrier: carrier_id).where('cbm_min <= ? AND cbm_max >= ? AND state = ?', cubic_size, cubic_size, gets_uf['uf'])

    self.price = price.last.value
    self.deadline = price.last.deadline
  end

  def gets_uf
    response = Faraday.get("https://viacep.com.br/ws/#{zip_code}/json/")
    JSON.parse(response.body)
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApiController
  def search
    code = params[:code]
    code && order = Order.find_by('code = ?', code)
    if order
      orderJson = order.as_json(except: %i[created_at updated_at vehicle_id])
      orderJson["updates"] = order.order_updates.as_json(except: %i[created_at updated_at])
      orderJson["vehicle"] = order.vehicle
      render status: 200, json: orderJson
    else
      render status: 404, json: { message: "not found"}
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update accept reject finish budgets]

  def index
    if current_user && !current_user.admin?
      @orders = current_user.carrier.orders.where(status: [1, 2, 4, 5, 6])
      @carrier = current_user.carrier
      @vehicles = current_user.carrier.vehicles
    else
      @orders = Order.all
    end
  end

  def new
    return unless current_user&.admin?

    @order = Order.new
    @carriers = Carrier.all
  end

  def create
    @carriers = Carrier.all
    params_order = params.require(:order).permit(:status, :code, :cubic_size, :pickup_address, :receiver_address,
                                                 :receiver_cpf, :receiver_name, :receiver_phone, :carrier_id,
                                                 :deadline, :price, :zip_code)
    @order = Order.new(params_order)
    if @order.save
      redirect_to orders_path, notice: 'Pedido registrado e enviado com sucesso'
    else
      render :new
    end
  end

  def accept
    order = Order.find(params[:id])
    order.status = 'Aceito'
    order.save
    redirect_to orders_path
  end

  def reject
    order = Order.find(params[:id])
    order.status = 'Recusado'
    order.save
    redirect_to orders_path
  end

  def select_vehicle
    order = Order.find(params[:id])
    order.vehicle_id = params[:vehicle_id]
    order.save
    redirect_to orders_path
  end

  def finish
    order = Order.find(params[:id])
    order.status = 'Finalizado'
    order.save
    redirect_to orders_path
  end

  def search
    current_user && @carrier = current_user.carrier

    @code = params['query']
    @code && @order = Order.find_by('code LIKE ?', "%#{@code}%")

    if @order
      @order_updates = @order.order_updates
    else
      redirect_to root_path, notice: 'Código não encontrado'
    end
  end

  def budgets
    current_user && @carrier = current_user.carrier
    @cubic_size = params[:cubic_size]
    @cep = params[:cep]

    return unless (@budgets = []) && Services.ask_cep(@cep)

    @budgets = Price.where('cbm_min <= ? AND cbm_max >= ? AND state = ?',
                           @cubic_size, @cubic_size, Services.ask_cep(@cep))
    @budgets.each do |budget|
      BudgetHistory.create(carrier: budget.carrier, freight: budget.value, deadline: budget.deadline,
                           zip_code: @cep, cubic_size: @cubic_size)
    end
  end
end

app/views/orders/_form.html.erb
<section class=' pt-20 flex justify-center items-center h-full px-[3%]'>
  <%= form_with model: @order, html: {class:' h-[90%] items-center flex'}, data: { turbo: false } do |f| %>
    <div class=' flex flex-col text-black bg-slate-300 justify-center items-center px-10 py-6 m-auto'>
      <h2 class=' text-2xl font-bold pb-4'>Cadastro de Transportadora</h2>
      <div class='flex flex-col'>
      <div class='field pb-3'>
        <%= f.label :zip_code %><br />
        <%= f.text_field :zip_code, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:zip_code).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :cubic_size %><br />
        <%= f.text_field :cubic_size, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:cubic_size).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :pickup_address %><br />
        <%= f.text_field :pickup_address, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:pickup_address).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :receiver_address %><br />
        <%= f.text_field :receiver_address, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:receiver_address).first %></p>
        <% end %>
      </div>
      <h1>Informações do destinatario</h1>
      <div class='field pb-5'>
        <%= f.label :receiver_name %><br />
        <%= f.text_field :receiver_name, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:receiver_name).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :receiver_cpf %><br />
        <%= f.text_field :receiver_cpf, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:receiver_cpf).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :receiver_phone %><br />
        <%= f.text_field :receiver_phone, class:'rounded-2xl' %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:receiver_phone).first %></p>
        <% end %>
      </div>

      <div class='field pb-5'>
        <%= f.label :carrier_id %><br />
        <%= f.collection_select :carrier_id, @carriers, :id, :fantasy_name %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:carrier_id).first %></p>
        <% end %>
      </div>

      <div class='button_send'>
        <%= f.submit 'Enviar', class: 'bg-blue-500 hover:bg-blue-700 text-white font-semibold py-1 px-3 rounded-xl text-sm cursor-pointer text-xl'%>
      </div>
    </div>
  </div>
  <% end %>
</section>

app/views/orders/budgets.html.erb
<div>
  <div class= 'flex justify-end mt-2'>
    <%= button_to 'Voltar', orders_path, method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl text-sm w-14'%>
  </div>

  <p class='font-semibold'>Resultados da busca para: <%= @cep%> | <%= @cubic_size%>M cúbicos
  <div class='pt-2'>
    <p class='pb-2 font-semibold'><%= @results.count %> <%= t(:result, count: @results.count) %> <%= t :found, count: @results.count %> </p>
    <% @results.each do |result| %>
      <div class='pt-1'>
        <%= result[:company] %> - frete <%= number_to_currency(result[:frete], unit: "R$") %> | <%= result[:deadline] %> dias úteis
      </div>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<section class='flex pt-28'>
  <div class='container flex flex-col lg:flex-row max-lg:items-center'>
    <div class= 'lg:w-2/12 pr-6 pb-6'>
      <% if current_user && current_user.admin? %>
        <%= button_to 'Cadastrar novo', new_order_path, method: :get, class: 'mt-2 bg-blue-500 hover:bg-blue-700 text-white px-2 py-1 rounded-xl text-sm mr-2 mb-5' %>
      <% end %>
      <%= form_with url: budgets_orders_path, method: :get do |f| %>
        <div>
          <h1 class='text-lg font-semibold pb-2'>Orçamento<h1>
          <div class='flex flex-col pr-4'>
            <div class='flex lg:flex-col'>
              <div class='flex flex-col mr-3'>
                <%= f.label :cubic_size %>
                <%= f.number_field :cubic_size, class:'rounded-lg h-7 w-28' %>
              </div>
              <div class='flex flex-col'>
                <%= f.label :cep %>
                <%= f.number_field :cep, class:'rounded-lg h-7 w-28' %>
              </div>
            </div>
            <div class='flex lg:flex-col max-lg:items-center max-lg:space-x-2'>
              <%= f.submit 'Buscar', class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl cursor-pointer w-20 my-3 '%>
              <%= link_to 'Historico', budget_histories_path, class: 'bg-gray-400 hover:bg-gray-500 text-white py-1 px-2 rounded-xl w-20 cursor-pointer' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class='orders-container grid md:w-[680px] lg:w-10/12 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3'>
      <% if @orders.empty? %>
      <p>Não há pedidos</p>
      <% else %>
        <% @orders.each do |order| %>
        <div class='order py-5 px-5 bg-slate-200 flex justify-self-stretch m-2'>
          <div class= 'flex flex-col'>
            <div>
              <p class=' text-lg font-semibold pb-4'>Pedido: <%= order.code %></p>
              <p class='font-bold'>Status: <%= Order.human_attribute_name("status.#{order.status}") %></p>
              <p>Dimensão em M cúbicos: <%= order.cubic_size %></p>
              <p>Endereço de retirada: <%= order.pickup_address %></p>
            </div>

            <div class='py-3'>
              <h1 class=' text-lg font-semibold'>Informações do destinatario</h1>
              <p>Nome: <%= order.receiver_name %></p>
              <p>Endereço de entrega: <%= order.receiver_address %></p>
              <p>CPF: <%= order.receiver_cpf %></p>
              <p>Telephone: <%= order.receiver_phone %></p>
            </div>

            <div class='pb-3'>
              <p>CEP: <%= order.zip_code %></p>
              <p>Frete: <%= order.price %></p>
              <p>Prazo: <%= order.deadline %> dias</p>
              <p>Transportadora: <%= order.carrier.fantasy_name %></p>
              <% if order.vehicle %>
                <p>Veiculo: <%= order.vehicle.model %> | <%= order.vehicle.plate %></p>
              <% end %>
            </div>

            <div>
              <div><%= button_to 'Ver detalhes de entrega', order_order_updates_path(order), method: :get, class: 'bg-gray-400 hover:bg-gray-500 text-white py-1 px-2 rounded-xl text-sm mr-2 ' %></div>
              <% if user_signed_in? && !current_user.admin? %>
                <div class= 'flex flex-col'>
                  <% if order.pendente? %>
                    <div class= 'flex mt-2'>
                      <%= button_to 'Aceitar', accept_order_path(order), method: :patch, class: 'bg-green-500 hover:bg-green-700 text-white py-1 px-2 rounded-xl text-sm w-20 mr-2 '%>
                      <%= button_to 'Recusar', reject_order_path(order), method: :patch, class: 'bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded-xl text-sm w-20  '%>
                    </div>
                  <% else %>
                    <div class= 'flex my-2'>
                      <%= button_to 'Finalizar', finish_order_path(order), method: :patch, class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl text-sm w-20 mr-2'%>
                      <%= button_to 'Atualizar', new_order_order_update_path(order), method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-1 rounded-xl text-sm w-20 ' %>
                    </div>
                  <% end %>
                </div>

                <div>
                  <% if !order.vehicle && !order.pendente? %>
                    <%= form_with url: select_vehicle_order_path(order), method: :patch do |f|%>
                      <%= f.label :vehicle_id %>
                      <%= f.collection_select :vehicle_id, @vehicles, :id, :plate%>
                      <%= f.submit 'Designar Veiculo', class: 'bg-blue-500 hover:bg-blue-700 text-white mt-2 py-1 px-2 rounded-xl cursor-pointer'%>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>

          </div>
        </div>
        <% end %>
    </div>
      <% end%>
  </div>
</section>

app/views/orders/new.html.erb
<%= render 'form'%>

app/views/orders/search.html.erb
<div>
  <% if @code && @order %>
  <div>
    Pedido <%= @order.code%> - Status: <%= @order.status%>
  </div>
  <% if @order.vehicle %>
    <div>
      <h1>Informações do veiculo</h1>
      <p><%= @order.vehicle.brand %> <%= @order.vehicle.model %> <%= @order.vehicle.plate %></p>
    </div>
  <% end %>
  <div>
    <% if !@order_updates.empty? %>
    <% @order_updates.each do |order_update| %>
      <div class=" pb-2">
        <%=l order_update.date %> - <%= order_update.hour %>
        De <%= order_update.last_location %> para <%= order_update.next_location %>
      </div>
    <% end %>
    <% else %>
      <p>Pedido ainda não foi enviado</p>
    <% end %>
  </div>
  <% end %>
</div>