config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get '/orders/search/:code', to: 'homepage#index'
  devise_for :users
  resources :budget_histories , only: [:index]
  resources :carriers, only: [:index, :new, :show, :new, :create, :edit, :update] do
    resources :vehicles, only: [:new, :create, :show]
    resources :prices, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :deadlines, only: [:new, :create, :edit, :update, :index, :destroy]
    patch 'inactivate', on: :member
    patch 'reactivate', on: :member
  end
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    resources :order_updates, only: [:index, :new, :create]
    member do
      patch 'accept'
      patch 'reject'
      patch 'select_vehicle'
      patch 'finish'
    end
    collection do
      get 'search'
      get 'budgets'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index] do
        collection do
          get '/search/:code', to: 'orders#search'
        end
      end
    end
  end
end

app/models/price.rb
class Price < ApplicationRecord
  validates :cbm_max, :cbm_min, :state, :value, presence: true

  belongs_to :carrier
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :authenticate_user!
  def index
    return unless current_user && !current_user.admin?

    @carrier = Carrier.find(params[:carrier_id])
    @prices = @carrier.prices
  end

  def new
    return unless current_user && !current_user.admin?

    @carrier = Carrier.find(params[:carrier_id])
    @prices = @carrier.prices
    @price = Price.new
  end

  def create
    return unless current_user && !current_user.admin?

    @carrier = Carrier.find(params[:carrier_id])
    @prices = @carrier.prices
    price_params = params.require(:price).permit(:cbm_max, :cbm_min, :value, :state, :carrier_id)
    @price = @carrier.prices.new(price_params)
    if @price.save
      redirect_to carrier_prices_path(@carrier)
    else
      render :new
    end
  end

  def edit
    return unless current_user && !current_user.admin?

    @carrier = Carrier.find(params[:carrier_id])
    @prices = @carrier.prices
    @price = Price.find(params[:id])
  end

  def update
    return unless current_user && !current_user.admin?

    @carrier = Carrier.find(params[:carrier_id])
    price_params = params.require(:price).permit(:cbm_max, :cbm_min, :state, :value, :carrier_id)
    @price = Price.find(params[:id])
    if @price.update(price_params)
      redirect_to carrier_prices_path(@carrier)
    else
      @prices = @carrier.prices
      render :edit
    end
  end

  def destroy
    @carrier = Carrier.find(params[:carrier_id])
    Price.find(params[:id]).destroy
    redirect_to carrier_prices_path(@carrier), notice: 'Preço apagado com sucesso!'
  end
end

app/views/prices/_list_new_edit.html.erb
<section  class=' pt-28 flex justify-center items-center h-full px-[3%]'>
<%= form_with model: [:carrier, @price], html: {class:' h-[90%] items-center flex'}, data: { turbo: false } do |f| %>
<div class=' flex flex-col text-black bg-slate-300 justify-center items-center px-10 py-6 m-auto'>
  <h2 class=' text-2xl font-bold pb-4'>Cadastro de Preços</h2>
  <div class='flex flex-col'>
    <div class='field pb-5'>
      <%= f.label :cbm_min %><br />
      <%= f.text_field :cbm_min, class:'rounded-2xl w-full mr-2' %>
      <% if @price.errors.any?%>
        <p class=' text-red-600'><%= @price.errors.full_messages_for(:cbm_min).first %></p>
      <% end %>
    </div>

    <div class='field pb-5'>
      <%= f.label :cbm_max %><br />
      <%= f.text_field :cbm_max, class:'rounded-2xl w-full mr-2' %>
      <% if @price.errors.any?%>
        <p class=' text-red-600'><%= @price.errors.full_messages_for(:cbm_max).first %></p>
      <% end %>
    </div>

    <div class='field pb-5'>
      <%= f.label :state %><br />
      <%= f.text_field :state, class:'rounded-2xl w-full mr-2' %>
      <% if @price.errors.any?%>
        <p class=' text-red-600'><%= @price.errors.full_messages_for(:state).first %></p>
      <% end %>
    </div>

    <div class='field pb-5'>
      <%= f.label :value %><br />
      <%= f.text_field :value, class:'rounded-2xl w-full mr-2' %>
      <% if @price.errors.any?%>
        <p class=' text-red-600'><%= @price.errors.full_messages_for(:value).first %></p>
      <% end %>
    </div>

    <div class='button_send'>
      <%= f.submit 'Enviar', class: 'bg-blue-500 hover:bg-blue-700 text-white font-semibold py-1 px-3 h-8 rounded-xl text-sm cursor-pointer text-xl'%>
    </div>
  </div>
</div>
<% end %>

</section>

app/views/prices/edit.html.erb
<%= render 'list_new_edit'%>

app/views/prices/index.html.erb
<section class=' pt-28 h-full px-[3%]'>
  <div>
    <div class= 'flex justify-between'>
    <%= button_to 'Cadastrar novo', new_carrier_price_path(@carrier), method: 'get' , class: 'mb-4 bg-green-500 hover:bg-green-700 text-white py-1 px-2 rounded-xl text-sm mr-2 '%>
    <%= button_to 'Voltar', root_path, method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded-xl text-sm w-14' %>
    </div>
    <% if @prices.empty?%>
    <div>
      <p>Não há Preços cadastrados</p>
    </div>
  <% elsif @prices%>
    <div class='bg-slate-300 p-5 flex justify-center'>
      <table class='prices min-w-[60%]  bg-slate-300 p-5'>
        <thead >
          <tr class=' text-left'>
            <th>Peso cubado</th>
            <th>Estado</th>
            <th>Valor</th>
            <th>Açoes</th>
          </tr>
        </thead>
        <tbody>
        <% @prices.each do |val|%>
            <tr>
              <td><%= val.cbm_min %> a <%= val.cbm_max %></td>
              <td><%= val.state %></td>
              <td><%=number_to_currency(val.value, unit: "R$")%></td>
              <td class='flex'><%=button_to 'Editar', edit_carrier_price_path(@carrier, val), method: 'get', class: 'bg-green-500 hover:bg-green-700 text-white px-2 rounded-xl text-sm w-16 mr-2 ' %>
              <%= button_to 'Excluir', carrier_price_path(@carrier, val), method: 'delete' , class: 'bg-red-500 hover:bg-red-700 text-white px-2 rounded-xl text-sm w-16 mr-2 ' %></td>
            </tr>
        <%end%>
        </tbody>
      </table>
    </div>
  <%end%>
  </div>
</section>

app/views/prices/new.html.erb
<%= render 'list_new_edit'%>