config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get '/orders/search/:code', to: 'homepage#index'
  devise_for :users
  resources :budget_histories , only: [:index]
  resources :carriers, only: [:index, :new, :show, :new, :create, :edit, :update] do
    resources :vehicles, only: [:new, :create, :show]
    resources :prices, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :deadlines, only: [:new, :create, :edit, :update, :index, :destroy]
    patch 'inactivate', on: :member
    patch 'reactivate', on: :member
  end
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    resources :order_updates, only: [:index, :new, :create]
    member do
      patch 'accept'
      patch 'reject'
      patch 'select_vehicle'
      patch 'finish'
    end
    collection do
      get 'search'
      get 'budgets'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index] do
        collection do
          get '/search/:code', to: 'orders#search'
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliverySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header id='menu' class='absolute top-0 w-full'>
      <div class='container'>
        <nav id='menu-desktop' class='w-full hidden lg:flex justify-between items-center'>
          <div class='flex items-center'>
            <div class='item'>
              <%= image_tag 'logo-white.png'%>
            </div>
            <div class='item_menu ml-2'>
              <%= link_to 'Home', root_path %>
            </div>
            <% if user_signed_in? && current_user.admin? %>
            <div class='item_menu mr-1'><%= link_to 'Transportadoras', carriers_path %></div>
            <div class='item_menu ml-1'><%= link_to 'Pedidos', orders_path %></div>
            <%  elsif user_signed_in? && !current_user.admin? %>
            <div class='item_menu ml-1'><%= link_to 'Dashboard', @carrier %></div>
            <div class='item_menu'><%= link_to 'Tabela de preços', carrier_prices_path(@carrier) %></div>
            <div class='item_menu ml-1'><%= link_to 'Pedidos', orders_path %></div>
            <% end %>
          </div>
          <% if user_signed_in? %>
          <div class='flex'>
            <div class='px-4'><%= current_user.email %></div>
            <div class=' text-red-600'><%= button_to 'Sair', destroy_user_session_path, method: 'delete' %></div>
          </div>
          <% else %>
          <div class=''><%= link_to 'Entrar', new_user_session_path %></div>
          <% end %>
        </nav>

        <nav class='flex lg:hidden w-full items-center justify-between'>
          <div id='btn-menu' class='flex items-center'>
            <i class="fa-solid fa-bars text-3xl"></i>
          </div>
          <div class='item'>
            <%= image_tag 'logo-white.png'%>
          </div>
          <div>
          </div>
          <div id='menu-mobile' class='bg-zinc-900 h-screen hidden flex-col items-center absolute top-[71px] left-0 px-6'>
            <div class='pb-3 pt-2 font-semibold text-lg'>
              <%= link_to 'Home', root_path %>
            </div>
            <% if user_signed_in? && current_user.admin? %>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Transportadoras', carriers_path %></div>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Pedidos', orders_path %></div>
            <%  elsif user_signed_in? && !current_user.admin? %>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Dashboard', @carrier %></div>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Tabela de preços', carrier_prices_path(@carrier) %></div>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Pedidos', orders_path %></div>
            <% end %>

            <% if user_signed_in? %>
              <div class='pb-3 font-semibold text-lg'><%= current_user.email %></div>
              <div class='pb-3 font-semibold text-lg text-red-600'><%= button_to 'Sair', destroy_user_session_path, method: 'delete' %></div>
            <% else %>
            <div class='pb-3 font-semibold text-lg'><%= link_to 'Entrar', new_user_session_path %></div>
            <% end %>
          </div>
        </nav>
      </div>
    </header>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>